const styles = {
    form: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        padding: '0rem 5rem',
        transition: 'all 0.2s 0.7s',
        overflow: 'hidden',
        gridColumn: '1 / 2',
        gridRow: '1 / 2',
    },
    title: {
        fontSize: '2.2rem',
        color: '#444',
        marginBottom: '10px',
    },
    inputField: {
        maxWidth: '380px',
        width: '100%',
        backgroundColor: '#f0f0f0',
        margin: '10px 0',
        height: '55px',
        borderRadius: '55px',
        display: 'grid',
        gridTemplateColumns: '15% 85%',
        padding: '0 0.4rem',
        position: 'relative',
    },
    icon: {
        textAlign: 'center',
        lineHeight: '55px',
        color: '#acacac',
        transition: '0.5s',
        fontSize: '1.1rem',
    },
    input: {
        background: 'none',
        outline: 'none',
        border: 'none',
        lineHeight: 1,
        fontWeight: 600,
        fontSize: '1.1rem',
        color: '#333',
    },
    socialText: {
        padding: '0.7rem 0',
        fontSize: '1rem',
    },
    socialMedia: {
        display: 'flex',
        justifyContent: 'center',
    },
    socialIcon: {
        height: '46px',
        width: '46px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        margin: '0 0.45rem',
        color: '#333',
        borderRadius: '50%',
        border: '1px solid #333',
        textDecoration: 'none',
        fontSize: '1.1rem',
        transition: '0.3s',
    },
    btn: {
        width: '150px',
        backgroundColor: '#5995fd',
        border: 'none',
        outline: 'none',
        height: '49px',
        borderRadius: '49px',
        color: '#fff',
        textTransform: 'uppercase',
        fontWeight: 600,
        margin: '10px 0',
        cursor: 'pointer',
        transition: '0.5s',
    },
    image: {
        width: '100%',
        transition: 'transform 1.1s ease-in-out',
        transitionDelay: '0.4s',
    }
};

export default styles